In [188]:
import pandas as pd

In [189]:
pd.set_option('display.max_columns', None)

In [190]:
df_obesidade = pd.read_csv('https://raw.githubusercontent.com/LuFeMa33/PosTech_DataVizProductModels/refs/heads/main/Obesity.csv')

In [191]:
df_obesidade.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [192]:
# Categórticas: 
# CAEC (Consumo de lancher/comes entre as refeições)
# CALC (Consumo de bebida alcoolica)
# MTRANS (Meio de transporte)

In [193]:
df_obesidade.shape

(2111, 17)

In [194]:
df_obesidade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [195]:
dict_colunas_alteracao = {'Gender':'Genero',
                          'Age':'Idade',
                          'Height':'Altura',
                          'Weight':'Peso',
                          'family_history':'historico_familiar',
                          'FAVC':'frequencia_consumo_alta_caloria',
                          'FCVC':'frequencia_consumo_vegetais',
                          'NCP':'numero_refeicoes_principais',
                          'CAEC':'consumo_lanches_entre_refeicoes',
                          'SMOKE':'fumante',
                          'CH2O':'consumo_agua',
                          'SCC':'monitoramento_consumo_calorias',
                          'FAF':'frequencia_atividade_fisica',
                          'TUE':'tempo_uso_dispositivos_eletronicos',
                          'CALC':'consumo_alcool',
                          'MTRANS':'meio_transporte',
                          'Obesity':'Obesidade'}

In [196]:
df_obesidade.rename(columns=dict_colunas_alteracao, inplace=True)

In [197]:
df_obesidade.head()

,Genero,Idade,Altura,Peso,historico_familiar,frequencia_consumo_alta_caloria,frequencia_consumo_vegetais,numero_refeicoes_principais,consumo_lanches_entre_refeicoes,fumante,consumo_agua,monitoramento_consumo_calorias,frequencia_atividade_fisica,tempo_uso_dispositivos_eletronicos,consumo_alcool,meio_transporte,Obesidade
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [198]:
df_obesidade['historico_familiar'] = df_obesidade['historico_familiar'].map({'yes': '1', 'no': '0'})
df_obesidade['frequencia_consumo_alta_caloria'] = df_obesidade['frequencia_consumo_alta_caloria'].map({'yes': '1', 'no': '0'})
df_obesidade['fumante'] = df_obesidade['fumante'].map({'yes': '1', 'no': '0'})
df_obesidade['monitoramento_consumo_calorias'] = df_obesidade['monitoramento_consumo_calorias'].map({'yes': '1', 'no': '0'})
df_obesidade['Indice_Genero'] = df_obesidade['Genero'].map({'Female':0, 'Male':1})

In [199]:
df_obesidade.head()

,Genero,Idade,Altura,Peso,historico_familiar,frequencia_consumo_alta_caloria,frequencia_consumo_vegetais,numero_refeicoes_principais,consumo_lanches_entre_refeicoes,fumante,consumo_agua,monitoramento_consumo_calorias,frequencia_atividade_fisica,tempo_uso_dispositivos_eletronicos,consumo_alcool,meio_transporte,Obesidade,Indice_Genero
0,Female,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight,0
1,Female,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,0
2,Male,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,1
3,Male,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I,1
4,Male,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,1

In [200]:
set(df_obesidade['Obesidade'])

{'Insufficient_Weight',
 'Normal_Weight',
 'Obesity_Type_I',
 'Obesity_Type_II',
 'Obesity_Type_III',
 'Overweight_Level_I',
 'Overweight_Level_II'}

In [201]:
set(df_obesidade['meio_transporte'])

{'Automobile', 'Bike', 'Motorbike', 'Public_Transportation', 'Walking'}

In [202]:
set(df_obesidade['consumo_lanches_entre_refeicoes'])

{'Always', 'Frequently', 'Sometimes', 'no'}

In [203]:
df_obesidade.head()

,Genero,Idade,Altura,Peso,historico_familiar,frequencia_consumo_alta_caloria,frequencia_consumo_vegetais,numero_refeicoes_principais,consumo_lanches_entre_refeicoes,fumante,consumo_agua,monitoramento_consumo_calorias,frequencia_atividade_fisica,tempo_uso_dispositivos_eletronicos,consumo_alcool,meio_transporte,Obesidade,Indice_Genero
0,Female,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight,0
1,Female,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,0
2,Male,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,1
3,Male,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I,1
4,Male,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,1

In [204]:
df_obesidade['IMC'] = (df_obesidade['Peso'] / (df_obesidade['Altura'])**2).round(3)

In [205]:
df_obesidade.head()

,Genero,Idade,Altura,Peso,historico_familiar,frequencia_consumo_alta_caloria,frequencia_consumo_vegetais,numero_refeicoes_principais,consumo_lanches_entre_refeicoes,fumante,consumo_agua,monitoramento_consumo_calorias,frequencia_atividade_fisica,tempo_uso_dispositivos_eletronicos,consumo_alcool,meio_transporte,Obesidade,Indice_Genero,IMC
0,Female,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight,0,24.387
1,Female,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,0,24.238
2,Male,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,1,23.765
3,Male,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I,1,26.852
4,Male,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,1,28.342

In [206]:
df_obesidade.head()

,Genero,Idade,Altura,Peso,historico_familiar,frequencia_consumo_alta_caloria,frequencia_consumo_vegetais,numero_refeicoes_principais,consumo_lanches_entre_refeicoes,fumante,consumo_agua,monitoramento_consumo_calorias,frequencia_atividade_fisica,tempo_uso_dispositivos_eletronicos,consumo_alcool,meio_transporte,Obesidade,Indice_Genero,IMC
0,Female,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight,0,24.387
1,Female,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,0,24.238
2,Male,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,1,23.765
3,Male,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I,1,26.852
4,Male,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,1,28.342

In [207]:
df_obesidade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Genero                              2111 non-null   object
 1   Idade                               2111 non-null   float64
 2   Altura                              2111 non-null   float64
 3   Peso                                2111 non-null   float64
 4   historico_familiar                  2111 non-null   object
 5   frequencia_consumo_alta_caloria     2111 non-null   object
 6   frequencia_consumo_vegetais         2111 non-null   float64
 7   numero_refeicoes_principais         2111 non-null   float64
 8   consumo_lanches_entre_refeicoes     2111 non-null   object
 9   fumante                             2111 non-null   object
 10  consumo_agua                        2111 non-null   float64
 11  monitoramento_consumo_calorias      2111 non-null   object
 12  frequencia_atividade_fisica         2111 non-null   float64
 13  tempo_uso_dispositivos_eletronicos  2111 non-null   float64
 14  consumo_alcool                      2111 non-null   object
 15  meio_transporte                     2111 non-null   object
 16  Obesidade                           2111 non-null   object
 17  Indice_Genero                       2111 non-null   int64
 18  IMC                                 2111 non-null   float64
dtypes: float64(9), int64(1), object(9)
memory usage: 313.5+ KB